---
- name: Terminate AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: EC2 Facts
    ec2_instance_facts:
      region: "{{ aws_region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"

      filters:
        instance-state-name: "running"
        "tag:Name": "lightning-node"

    register: ec2
  - debug: var=ec2

  - name: Kill EC2 Instance
    ec2:
      instance_ids: "{{ ec2.instances[0].instance_id }}"
      state: "absent"
      region: "{{ aws_region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
